version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - xyz-network

  # IdentityServer
  identityserver:
    build: ./IdentityServer
    ports:
      - "5153:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - xyz-network

  # Main API
  api:
    build: ./xyz-university-payment-api
    ports:
      - "5260:80"
    depends_on:
      - sqlserver
      - identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UniversityDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
    networks:
      - xyz-network

volumes:
  sqlserver_data:

networks:
  xyz-network:
    driver: bridge 