version: '3.8'

services:
  xyz-university-api:
    image: ghcr.io/${GITHUB_REPOSITORY:-ak-2002/xyz-university-payment-api}/xyz-university-payment-api:develop
    container_name: xyz-university-api-dev
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver-dev;Database=XYZUniversityDB;User Id=sa;Password=DevPassword123!;TrustServerCertificate=true
      - ConnectionStrings__Redis=redis-dev:6379
      - Redis__InstanceName=xyz-university-api-dev:
    depends_on:
      - sqlserver-dev
      - redis-dev
    networks:
      - xyz-university-network
    restart: unless-stopped

  sqlserver-dev:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - SA_PASSWORD=DevPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data_dev:/var/opt/mssql
    networks:
      - xyz-university-network
    restart: unless-stopped

  redis-dev:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - xyz-university-network
    restart: unless-stopped

  rabbitmq-dev:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-dev
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data_dev:/var/lib/rabbitmq
    networks:
      - xyz-university-network
    restart: unless-stopped

  identity-server-dev:
    image: ghcr.io/${GITHUB_REPOSITORY:-ak-2002/xyz-university-payment-api}/identity-server:develop
    container_name: identity-server-dev
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver-dev
    networks:
      - xyz-university-network
    restart: unless-stopped

volumes:
  sqlserver_data_dev:
  redis_data_dev:
  rabbitmq_data_dev:

networks:
  xyz-university-network:
    driver: bridge 